global:
  scrape_interval:     15s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s  # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default value (10s).
  external_labels:
    cluster: 'tidb-cluster'
    monitor: "prometheus"

scrape_configs:
  - job_name: 'overwritten-nodes'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'node-exporter:9100'
  
  - job_name: 'placement-driver-server-1'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'placement-driver-server-1:2379'

  - job_name: 'placement-driver-server-2'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'placement-driver-server-2:2379'

  - job_name: 'placement-driver-server-3'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'placement-driver-server-3:2379'

  - job_name: 'tikv-server-1'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tikv-server-1:20180'

  - job_name: 'tikv-server-2'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tikv-server-2:20180'

  - job_name: 'tikv-server-3'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tikv-server-3:20180'

  - job_name: 'tidb-server'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tidb-server:10080'
  
  - job_name: 'tiflash-server-1'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tiflash-server-1:8234'

  - job_name: 'tiflash-server-2'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tiflash-server-2:8234'

  - job_name: 'tiflash-server-3'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tiflash-server-3:8234'

rule_files:
  - 'pd.rules.yml'
  - 'tikv.rules.yml'
  - 'tidb.rules.yml'

